apiVersion: v1
kind: Secret
metadata:
  name: fcg-orders-secret
type: Opaque
stringData:
  ConnectionStrings__FCGUsersDbConnection: "${FCG_DB_CONNECTION_STRING}"
  ConnectionStrings__FCGServiceBusConnection: "${FCG_SERVICEBUS_CONNECTION_STRING}"
  ConnectionStrings__FCGRabbitMQConnection: "${FCG_RABBITMQ_CONNECTION_STRING}"
  GamesApi__AuthToken: "${GAMES_API_AUTH_TOKEN}"
  GamesApi__SubscriptionKey: "${GAMES_API_SUBSCRIPTION_KEY}"
  NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
